@host=http://localhost:3001/api/notes

GET {{host}}

###

GET {{host}}/3

###

DELETE {{host}}/2

###

POST {{host}}
Content-Type: application/json

{ "content": "I hate javascript", "important": false}

###
